### ISSUE TITLE
What kind of files are these?

### ISSUE THREAD

**Issue by diffractometer** [jbeuckm/EFM_VCF3#1]
I do not know.

**Comment by jbeuckm** [comment]
eagle pcb schematic and board layout - all fit into the free version

**Comment by jbeuckm** [comment]
the *.nc files are gcode for etching the boards. i haven't figured out how to make github call them gcode yet with .gitattributes

**Comment by jbeuckm** [comment]
hijack: how do i get github to acknowledge G-Code files?

**Comment by diffractometer** [comment]
Hmm email support? lol. :smile:
